### ISSUE TITLE
Debug configuration does not add "d" suffix to libraries

### ISSUE THREAD

**Issue by Ri0n** [frankosterfeld/qtkeychain#109]
Hi

I'm compiling like this

```
cmake -G "Visual Studio 14 2015 Win64"  -Wno-dev -DCMAKE_PREFIX_PATH=C:\msvc\x64 -DCMAKE_INSTALL_PREFIX=C:/Qt/5.9.4/msvc2015_64/ --config debug .
cmake --build . --config debug
cmake --build . --config debug --target INSTALL
```

Installation looks like following

```
  -- Install configuration: "debug"
  -- Installing: C:/Qt/5.9.4/msvc2015_64/translations/qtkeychain_de.qm
  -- Installing: C:/Qt/5.9.4/msvc2015_64/translations/qtkeychain_ro.qm
  -- Installing: C:/Qt/5.9.4/msvc2015_64/include/qt5keychain/keychain.h
  -- Installing: C:/Qt/5.9.4/msvc2015_64/include/qt5keychain/qkeychain_export.h
  -- Installing: C:/Qt/5.9.4/msvc2015_64/lib/qt5keychain.lib
  -- Installing: C:/Qt/5.9.4/msvc2015_64/bin/qt5keychain.dll
  -- Installing: C:/Qt/5.9.4/msvc2015_64/mkspecs/modules/qt_Qt5Keychain.pri
  -- Installing: C:/Qt/5.9.4/msvc2015_64/lib/cmake/Qt5Keychain/Qt5KeychainLibraryDepends.cmake
  -- Installing: C:/Qt/5.9.4/msvc2015_64/lib/cmake/Qt5Keychain/Qt5KeychainLibraryDepends-debug.cmake
  -- Installing: C:/Qt/5.9.4/msvc2015_64/lib/cmake/Qt5Keychain/Qt5KeychainConfig.cmake
  -- Installing: C:/Qt/5.9.4/msvc2015_64/lib/cmake/Qt5Keychain/Qt5KeychainConfigVersion.cmake
```

Debug configuration should add "d" suffix to qt5keychain.dll and qt5keychain.lib as it's done for Qt libraries.

---

Btw, windeployqt doesn't work when qt5keychain is installed into different prefix, but it's a topic for another report.

**Comment by guruz** [comment]
> Btw, windeployqt doesn't work when qt5keychain is installed into different prefix, but it's a topic for another report.

I think that's normal, windeployqt doesn't pick up the OpenSSL libraries either if they're not in the Qt dir.

**Comment by Ri0n** [comment]
> I think that's normal, windeployqt doesn't pick up the OpenSSL libraries either if they're not in the Qt dir.

With openssl yes.  But in case of qtkeychain windeployqt exits with error and doesn't copy even Qt libs.

**Comment by Ri0n** [comment]
A workaround for the problem is to pass `-DCMAKE_DEBUG_POSTFIX=d` to cmake. 
But this has to be done automatically if no any different suffix explicitly set on command line.

**Comment by Ri0n** [comment]
Something like this https://github.com/signalapp/libsignal-protocol-c/pull/63/commits/2977115b2ce6f6ab40b3eb0509e7aa6897718101

**Comment by frankosterfeld** [comment]
Fixed by referenced commits.
