### ISSUE TITLE
libsecret and gnome-keyring backends are not compatible

### ISSUE THREAD

**Issue by yan12125** [frankosterfeld/qtkeychain#114]
I'm using Arch Linux, which recently upgraded qtkeychain from 0.8 to 0.9. Besides version bumping, the Arch Linux maintainer also [re-enabled the libsecret backend](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/qtkeychain&id=8a2b13020ea2e6819ca0ce91a9775dd026138205), and I noticed that applications are asking passwords again.

I have libsecret installed and gnome-keyring running. From `dbus-monitor` outputs, a request to the secret service from qtkeychain 0.9 is: (my server hostname redacted)
```
method call time=1531547236.561951 sender=:1.51 -> destination=:1.21 serial=10 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "user"
         string "yen_clientCertificatePEM:https://foobar.com/:0"
      )
      dict entry(
         string "server"
         string "ownCloud"
      )
      dict entry(
         string "type"
         string "plaintext"
      )
      dict entry(
         string "xdg:schema"
         string "org.qt.keychain"
      )
   ]
```

For qtkeychain 0.8, the request is:
```
method call time=1531547516.055992 sender=:1.64 -> destination=org.freedesktop.secrets serial=6 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "user"
         string "yen_clientCertificatePEM:https://foobar.com/:0"
      )
      dict entry(
         string "server"
         string "ownCloud"
      )
      dict entry(
         string "type"
         string "plaintext"
      )
   ]
```

Looks like they are not compatible. Is there a way to migrate from libgnome-keyring to libsecret without re-entering passwords?

**Comment by ckamm** [comment]
@yan12125 Thanks for the report. It's really unfortunate that the same password isn't accessed through both APIs.

@frankosterfeld It looks like one needs to use `SECRET_SCHEMA_COMPAT_NETWORK` as a schema to be able to read the passwords stored through `libgnome-keychain`. QtKeychain currently uses its own schema and thus can't read the old passwords.

Switching the schema at this point would likely make existing users lose access to their passwords. What could be done is to query the backwards compatible schema if the query with the custom schema fails in the libsecret backend?

**Comment by ckamm** [comment]
@yan12125 PR #117 solves the problem for me. Would you be up for double checking my tests? (if building from source is easy for you)

**Comment by yan12125** [comment]
I applied this patch on qtkeychain 0.9.0. The built package can read credentials saved by qtkeychain 0.8.0 (using libgnome-keyring) and qtkeychain 0.9.0 (using libsecret). Thanks a lot for the efforts!

**Comment by guruz** [comment]
@yan12125 Thanks for testing!

**Comment by yan12125** [comment]
As #117 is merged I consider this bug fixed. I'm still looking forward to a new release including that fix :)

**Comment by MaxXor** [comment]
Could you please release a new version which includes this fix? Thanks! :)

**Comment by MaxXor** [comment]
Thanks @guruz please update the Arch package.
