### ISSUE TITLE
Why isn't kwallet_interface present in the repo?

### ISSUE THREAD

**Issue by pajah1** [frankosterfeld/qtkeychain#120]
The KWallet implementation requires `kwallet_interface` `.h` and `.cpp` files. Of course they can be generated from `xml` while building via `cmake`, however what's the point of **not** including pre-generated `kwallet_interface` `.h` and `.cpp` files in this repo?

**Comment by ogoffart** [comment]
Automatically generated files usually does not belong in the repository. They are generated as part of the build process and have no reason to be checked in. They are just bloating the repository and create spurious changes. They can also get out of sync with the original.

Further reading:
https://softwareengineering.stackexchange.com/questions/192113/do-i-check-generated-code-in-to-source-control-or-not

**Comment by pajah1** [comment]
@ogoffart Thanks for the answer!
