### ISSUE TITLE
Cannot open include file: 'keychain.h': No such file or directory Error

### ISSUE THREAD

**Issue by keakarsu** [frankosterfeld/qtkeychain#132]
Hi There,

While I'm building nextcloud app it throws me an error which "Cannot open include file: 'keychain.h': No such file or directory Error" . I built QtKeychain successfully and  add path to system variables.

Do you have any suggestion for me ?

**Comment by keakarsu** [comment]
Oh my bad.

Thanks for yout advice..

iPhone’umdan gönderildi

Frank Osterfeld <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (25 Oca 2019 14:35):


That sounds more like a question towards owncloud. You probably have to tell cmake where to look for the cmake file, -DCMAKE_PREFIX_PATH=$qtkeychaininstalldir, or such.

**Comment by Jxzcode** [comment]
C:\work\Nextcloud-Desktop\build\src\libsync\nextcloudsync_autogen\include_Debug\LEWYVFTDK4\../../../../../../src/libsyn
c/creds/keychainchunk.h(20,10): fatal error C1083: Cannot open include file: 'qt5keychain/keychain.h': No such file or
directory [C:\work\Nextcloud-Desktop\build\src\libsync\nextcloudsync.vcxproj]
