### ISSUE TITLE
About QKeychain_Export

### ISSUE THREAD

**Issue by keakarsu** [frankosterfeld/qtkeychain#136]
Hi There,

While I'm trying to build a project it throws me 
"Cannot open include file: 'qkeychain_export.h': No such file or directory" 
I'm not sure it is about qtkeychain but I'm not able to find any solution.
Is there anybody knows the solution?

**Comment by SlySven** [comment]
Which OS are you on - IIRC Windows needs to put an extra compiler attribute on to functions that declared in the header file(s) and which get exported from the compiled lib and those (may) be different between when the header file(s) are compiled into the library being built and when they are subsequently used when something else links to that compiled library.

That `qkeychain_export.h` file, which does this, is actually *created* by the project's (top level) `./CMakeList.txt` project file for Windows builds - but I see that it seems to be added (along with `keychain.cpp` and keychain.h`) to the `qtkeychain_SOURCES` CMake project variable - for ALL target OSes - which to my mind seems suspicious!

Also the QMake project file `./qt5keychain.pri` doesn't do this - either `qmake` does the extra thing for Windows library header files automagically - or it is missing from the project (or maybe QMake is not a supported build system for Windoze?) 🤷‍♀️

**Comment by frankosterfeld** [comment]
@SlySven About QMake: The .pri file is meant for building qtkeychain directly into the application, not for building qtkeychain as separate shared library, so no symbol export is needed there. -DQTKEYCHAIN_NO_EXPORT should prevent that include error. That said, I'm not sure how many users use the .pri file (I myself use qtkeychain only in CMake projects) and whether bugs in there would be noticed...

" but I see that it seems to be added [...] - for ALL target OSes - which to my mind seems suspicious!"

Also the non-Windows platforms have`-fvisibility=hidden`, and symbols are explicitly exported there as well.

**Comment by frankosterfeld** [comment]
Closing, the export file is generated by CMake - please provide more information about the build steps should there still be an issue.
