### ISSUE TITLE
Broken on macOS Mojave if installed via Homebrew

### ISSUE THREAD

**Issue by aaronraimist** [frankosterfeld/qtkeychain#146]
If I install via Homebrew and then build a package that requires QtKeychain I get this error:
```
make[2]: *** No rule to make target `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework', needed by `spectral.app/Contents/MacOS/spectral'.  Stop.
make[1]: *** [CMakeFiles/spectral.dir/all] Error 2
make: *** [all] Error 2
```

For some reason it is trying to look in Xcode-beta.app even if I don't have that installed. Manually compiling QtKeychain works.

**Comment by frankosterfeld** [comment]
How is this related to qtkeychain? Is it still in issue now?

**Comment by aaronraimist** [comment]
Hmm I honestly can't remember. I'll reopen if I get more info.
