### ISSUE TITLE
Getting this error "fatal error LNK1112"

### ISSUE THREAD

**Issue by larslight11** [frankosterfeld/qtkeychain#155]
I tried to build my QTKEYCHAIN with the msvc2017_64 but it didnt work started giving me this error 

```
"C:\qtkeychain\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\qtkeychain\build\qt5keychain.vcxproj" (default target) (3) ->
(Link target) ->
  Qt5Cored.lib(Qt5Cored.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
[C:\qtkeychain-0.8.0\build\qt5keychain.vcxproj]

    0 Warning(s)
    1 Error(s)
```
So i built it with the 32 bit msvc2017 , then only it worked but now im having errors in my nextcloud build because im building for 64bit and the QTKEYCHAIN libraries are 32bit built .

someone please help me to build this for 64 bit .

**Comment by frankosterfeld** [comment]
I would suggest to use the command line prompt for msvc 64 bit and run cmake with `-GNinja` or nmake makefiles. Otherwise this is generic CMake buildsystem setup, not sure how to help here, closing.
