### ISSUE TITLE
Qt 6 support

### ISSUE THREAD

**Issue by frankosterfeld** [frankosterfeld/qtkeychain#175]
Qtkeychain itself seems to work fine with Qt 6 (at least on Mac), but the build system needs some thought:

Supporting Qt 4 and Qt 5 in the CMakeLists.txt is ugly enough already, adding yet another Qt version won't make it prettier. Maybe it's time to drop Qt 4 support.

Also, right now Qt 5 has priority over Qt 4 if Qt 5 is found, unless one explicitly enforces Qt 4. Question is if we should do Qt 6 > Qt 5 in a similar way, or leave Qt 5 as the default for now.

**Comment by KitsuneRal** [comment]
I'd rather keep Qt 5 for the default; Qt 6 is not entirely backwards compatible and it will take time for applications to move over. The nearest (and on par with Qt 5 in terms of modules) LTS version in Qt 6 is expected to be 6.2 - perhaps then it will be a good moment to change the defaults?

**Comment by frankosterfeld** [comment]
Done in 0.12 - Qt 5 is still default, BUILD_WITH_QT6 must be passed explicitly atm. Qt 4 support has been dropped.
