### ISSUE TITLE
Updates to qmake project file needed

### ISSUE THREAD

**Issue by SlySven** [frankosterfeld/qtkeychain#178]
With the switch to Qt 5 as a minimum your Qt qmake file (`qt5keychain.pri`) will likely need updating as well, to include something like at least:
```sh
lessThan(QT_MAJOR_VERSION, 5) {
    error("qtkeychain requires Qt 5 or later")
}
```

**Comment by frankosterfeld** [comment]
Added the minimum version check, "qt5keychain.pri" is also a somewhat unfortunate name, probably it should just drop the "5" and be "qtkeychain.pri". That can break people's builds though...
