### ISSUE TITLE
Use BUILD_SHARED_LIBS instead of QTKEYCHAIN_STATIC?

### ISSUE THREAD

**Issue by KitsuneRal** [frankosterfeld/qtkeychain#180]
Is there any particular reason why `QTKEYCHAIN_STATIC` is used in order to switch between static/shared library instead of [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)? Is it just to build a shared library by default?

**Comment by frankosterfeld** [comment]
That seems to be the cleaner way indeed. One might keep QTKEYCHAIN_STATIC around as "alias" to not break people's builds although that somehow defeats the purpose of the cleanup...

**Comment by KitsuneRal** [comment]
I think both can be supported for some transition perioud, with `QTKEYCHAIN_STATIC` only respected `if (!DEFINED BUILD_SHARED_LIBS)` (i.e., `BUILD_SHARED_LIBS` is literally unset, not just 0 or `false`).

**Comment by Be-ing** [comment]
Fixed in #204
