### ISSUE TITLE
Windows: Use CredWrite & CredRead

### ISSUE THREAD

**Issue by enko** [frankosterfeld/qtkeychain#22]
As of Windows 7 there is a [credential manager](http://windows.microsoft.com/en-us/windows7/what-is-credential-manager).

The corresponding API is [CredRead](http://msdn.microsoft.com/en-us/library/windows/desktop/aa374804%28v=vs.85%29.aspx) and [CredWrite](http://msdn.microsoft.com/en-us/library/windows/desktop/aa375187%28v=vs.85%29.aspx).

Functions taken from here:

http://stackoverflow.com/questions/9221245/how-do-i-store-and-retrieve-credentials-from-the-windows-vault-credential-manage

Would be very cool if this project could support this.

**Comment by akallabeth** [comment]
@enko @frankosterfeld This should be fix with my pull.

**Comment by guruz** [comment]
@frankosterfeld Can this issue be closed?
https://github.com/frankosterfeld/qtkeychain/blob/master/keychain_win.cpp#L19
