### ISSUE TITLE
Feature request: Add method if a backend is available

### ISSUE THREAD

**Issue by hefee** [frankosterfeld/qtkeychain#224]
In an application (kmail) I want to know, if there is a safe backend available, to start a migration from unsafe password storage in config file.

Before we used KWallet directly and could do [`KWallet::isEnabled()`](https://invent.kde.org/pim/kmailtransport/-/blob/master/src/kmailtransport/transport.cpp#L190) in order to trigger the migration [migrateToWallet()](https://invent.kde.org/pim/kmailtransport/-/blob/master/src/kmailtransport/transport.cpp#L273)

**Comment by michaelk83** [comment]
KeePassXC is exposed to client applications via the standard [Secret Service API](https://specifications.freedesktop.org/secret-service/latest/), which is also supported by Gnome Keyring, and more recently by KWallet itself (as of 5.97). There are standard ways in Linux to check whether that API (or any other DBus API) is available; and if a backend is already running, to check which backend process owns the API.

While it is possible to add another method to KeePassXC's own DBus API to query the state of its Secret Service integration, I don't see the advantage in doing so. As noted, Secret Service can be provided by many different backends (though not at the same time), so a global method to check its availability would be more useful IMO (and already exists).

One final note: if you are a developer of the client application, and it is a KDE application (such as kmail), then you should really be migrating it to [QtKeyChain](https://github.com/frankosterfeld/qtkeychain) instead. QtKeyChain abstracts the backend, and will select one automatically.
