### ISSUE TITLE
Need a new tag soon?

### ISSUE THREAD

**Issue by redstrate** [frankosterfeld/qtkeychain#244]
Good afternoon, I noticed a pretty nasty thing while testing out KDE Plasma 6. The last tag is 0.14.1 (which is before https://github.com/frankosterfeld/qtkeychain/commit/c3ce62c142700d02432414c2452f62c986867b9e) but this tag is also unusable on Plasma 6 currently. This is because `KDE_SESSION_VERSION` is now 6 and that fails the if check before that commit and it fails to read from KWallet, not even trying the kwalletd5 interface at all.

**Comment by frankosterfeld** [comment]
Thanks for the nagging, done!
