### ISSUE TITLE
Investigate Secret Service API

### ISSUE THREAD

**Issue by danimo** [frankosterfeld/qtkeychain#37]
GNOME Keyring has recently been deprecated in favor of libsecret, claiming its API is now stable. KDE also support the same standard that libsecret is based on (http://standards.freedesktop.org/secret-service/). Details can be found in [this LWN article](https://lwn.net/Articles/490518/).

**Comment by karolherbst** [comment]
I toyed around with libsecret and it works just fine with gnome-keyring, but it doesn't work with kwallet-4 nor kwallet-5

**Comment by frankosterfeld** [comment]
Do you know if the implementation in KDE5 is incomplete or just buggy/incompatible?

**Comment by karolherbst** [comment]
I really don't know. I only know that kwallet-5 has the same dbus API. Maybe it is just missig or maybe the idea was dropped entirely.

**Comment by guruz** [comment]
Is this done by https://github.com/frankosterfeld/qtkeychain/pull/62 ?

**Comment by azrdev** [comment]
@guruz the PR claims so, at least
