### ISSUE TITLE
KWallet5 support

### ISSUE THREAD

**Issue by karolherbst** [frankosterfeld/qtkeychain#46]
I've already created a bug report for https://github.com/owncloud/mirall/issues/2546 but I guess this is a qtkeychain issue. Currently it wokrs fine with kwallet4, but because I don't want to have both at the same time, because of runtime issues, I've removed kwallet4.

**Comment by klaasb** [comment]
Hi, I just did a short test. Basically all that is need is a s/kwalletd/kwalletd5/g in keychain_unix.cpp.
I don't currently have time to whip up a patch that sensibly keeps both options around, since there are quite some KDE4 references strewn around.

**Comment by karolherbst** [comment]
ahh, so its not that bad. Yeah maybe I find some time and could take a look too.
