### ISSUE TITLE
new release requested because kwallet5 support

### ISSUE THREAD

**Issue by karolherbst** [frankosterfeld/qtkeychain#50]
Plasma5 users really need a new qtkeychain release, so that applications (like dropbox) can use the new kwallet daemon, which helps users to remove the old kwallet daemon completly from the system.

**Comment by frankosterfeld** [comment]
Done: https://github.com/frankosterfeld/qtkeychain/releases/tag/v0.5.0

**Comment by karolherbst** [comment]
thanks a lot
