### ISSUE TITLE
Short documentation?

### ISSUE THREAD

**Issue by LarsBV** [frankosterfeld/qtkeychain#52]
It would be nice if there was some documentation. To explain when 
setAutoDelete(), setKey() etc. should be used. If there are any best practices etc.

can settings() be used to have a QSettings object backed by a secure storage or is this the insecure storage fallback ? 

should ReadPasswordJob be created everytime a value is needed or can it be reused by changing the key?

**Comment by Leont** [comment]
:+1:

**Comment by aelog** [comment]
@LarsBV 
PR #90 addresses most of your questions.

**Comment by LarsBV** [comment]
Cool, thanks :)
