### ISSUE TITLE
QT_TRANSLATIONS_DIR fix prevents the usage of a custom installation prefix

### ISSUE THREAD

**Issue by d1saster** [frankosterfeld/qtkeychain#54]
In c5533ae6836e7a39b282678489ca1e031795ae21 a call to install uses the QT_TRANSLATIONS_DIR variable, which does not necessarily resolve to a path within the CMAKE_INSTALL_PREFIX. The latter of course breaks installations where the installation directories of QT and qtkeychain differ and the user does not have permissions to access QT_TRANSLATIONS_DIR.

**Comment by pasnox** [comment]
Still present in 0.9 branch

**Comment by KitsuneRal** [comment]
Duplicate of #42?
