### ISSUE TITLE
qtkeychain fails to initialize kwalletd

### ISSUE THREAD

**Issue by sirio81** [frankosterfeld/qtkeychain#67]
I encounter an issue related to owncloud client project that is using qtkeychain.
https://github.com/owncloud/client/issues/4601#issuecomment-200356088

Summary:
(On debian 8 kde 4.14.2)
The error 'no keychain service available' is shown by the client when it tries to connect to kwalletd.
If kwalletd is running, it success.
I asked kde-devel about it:

> kwalletd is started on-demand through dbus activation [1] when one
> tries to use the org.kde.kwalletd(5) bus name. If it is not started
> dbus is not set up correctly or the service files are missing or
> qtkeychain manages to somehow not trigger dbus activation. 
> https://www.freedesktop.org/wiki/IntroductionToDBus/#activation

Could you please check why libqtkeychain fails to open kwalletd?

**Comment by krukai** [comment]
Confirmed for still being present and also happening with the Nextcloud client.

The work-around to this issue is starting kwalletd manually.

**Comment by frankosterfeld** [comment]
Closing this, please reopen if it still applies.
