### ISSUE TITLE
kwallet broken

### ISSUE THREAD

**Issue by olear** [frankosterfeld/qtkeychain#68]
Kwallet has been broken since https://github.com/frankosterfeld/qtkeychain/commit/e6e828c33b09f84a954f9885d0b4efd706bcd439

https://github.com/frankosterfeld/qtkeychain/blob/master/keychain_unix.cpp#L329
https://github.com/frankosterfeld/qtkeychain/blob/master/keychain_unix.cpp#L464

https://github.com/olear/qtkeychain/commit/36592711fc1f2666deebb9ded17f33f4437e0fdb

**Comment by frankosterfeld** [comment]
Looks good (and confirmed to fix the issues), pushed it to master in 36592711. Thanks!
