### ISSUE TITLE
testclient segfault on 'store' in KDE5 (kwallet)

### ISSUE THREAD

**Issue by olear** [frankosterfeld/qtkeychain#69]
Been testing qtkeychain for possible use in an application.

Currently I have tested it on

- GNOME2 (CentOS 6.7)
- GNOME3 (Fedora 23)
- Unity (Ubuntu 16.04)
- KDE4 (CentOS 7.2)
- OSX (10.6)
- Windows (7)

And seems to work fine, but I have issues on KDE5 (Fedora 23).

The testclient segfault after 'store' (the value is stored in kwallet), I can 'restore' the password without any problems. Is this a known issue? Will do a proper test a bit later today (with more info).

**Comment by frankosterfeld** [comment]
That's with current master (i.e. your patch) I assume? I've tested successfully on Kubuntu 15.10 (KDE frameworks 5.15.0) yesterday before merging.

**Comment by olear** [comment]
Yes, using current master. Will test on Kbuntu and also do a debug build with backtrace.

**Comment by olear** [comment]
Same issue in Kubuntu 15.10 (clean install).

Note I build against Qt4, but that should not matter(?)

Testbuild with the libraries I will use on deployment (also tested with native qt4 libs, same issue):
```
wget http://downloads.natron.fr/~olear/qtkeychain-linux64.tar.gz
tar xvf qtkeychain-linux64.tar.gz
cd qtkeychain-linux64
export LD_LIBRARY_PATH=.
./testclient store foo bar
```
Running it through gdb points to https://github.com/frankosterfeld/qtkeychain/blob/master/keychain_unix.cpp#L474

**Comment by frankosterfeld** [comment]
Hmm, maybe the reply is invalid? I was testing with Qt 5.

**Comment by olear** [comment]
Yes, adding a if (reply.isValid()) makes it work.

**Comment by frankosterfeld** [comment]
Makes it actually work, or just not crash?

**Comment by olear** [comment]
I get a positive result. 

The value was already saved before the segfault, so that didn't change. Will check a bit more later today to verify that everything is ok.

**Comment by frankosterfeld** [comment]
I merged your check for validity and released 0.6.2 with it. Looks good to me (I could reproduce the issue on a fresh Debian Jessie install and can also confirm that your patch fixes it)

**Comment by olear** [comment]
Great, sorry for not doing a pull request, but I'm currently integrating qtkeychain in our application, so I needed to do some modifications (we need qmake).

So currently things seems ok, there are some minor issues left with kwallet, mainly during the password prompt, if I wait too long then dbus seems too loose the connection and everything fails.

**Comment by frankosterfeld** [comment]
Ah, right, I remember dbus timeouts from other occasions... if one can detect the timeout properly, we could just start another request...
