### ISSUE TITLE
error compiling qtkeychain

### ISSUE THREAD

**Issue by linamu** [frankosterfeld/qtkeychain#71]
hi,
i'm trying to compile qtkeychain on ubuntu 14.04 and this is what i got 

CMake Error at /lib/cmake/Qt5Core/Qt5CoreConfig.cmake:27 (message):
  The imported target "Qt5::Core" references the file

```
 "//bin/qmake"
```

  but this file does not exist.  Possible reasons include:

i need help plz

**Comment by frankosterfeld** [comment]
That looks weird, usually it would be /usr/bin/qmake. Is there any qmake in your PATH? Did you install the Qt development packages?

**Comment by linamu** [comment]
how to know what's in my path plz ?

**Comment by linamu** [comment]
i now have this : 

 The imported target "Qt5::Core" references the file

     "//include/QtCore"

  but this file does not exist.  Possible reasons include:

**Comment by frankosterfeld** [comment]
Looks like some prefix cannot be detected by CMake. Please make sure you can compile and run a basic Qt application on that system before continuing with qtkeychain.

**Comment by linamu** [comment]
yes i do, i can compile Qt application

**Comment by frankosterfeld** [comment]
Ok, which exact line did you use when running cmake?

**Comment by linamu** [comment]
sudo cmake .

**Comment by frankosterfeld** [comment]
Try without sudo (one should never have to build as root anyway) and from a separate build directory, like

mkdir build
cd build
cmake ..

Not sure if that helps though. For more remote debugging I'd probably need cmake logs.

**Comment by linamu** [comment]
without sudo : CMake Error: : System Error: Permission denied
 cmake in "build" gives me the same error

**Comment by frankosterfeld** [comment]
make sure the source directory is owned by your normal user, and not root.

**Comment by linamu** [comment]
yes it's owned by another user

**Comment by frankosterfeld** [comment]
Do a clone with the same user who is then running cmake afterwards.

**Comment by linamu** [comment]
@frankosterfeld is it possible to compile qtkeychain on openwrt ?

**Comment by frankosterfeld** [comment]
If Qt builds, qtkeychain should, too (although it won't do much unless you have kwallet or gnome keyring installed as well).. The error is expected if you build owncloud client without having qtkeychain compiled and installed before.

**Comment by linamu** [comment]
@frankosterfeld how to compile qtkeychain on openwrt?

**Comment by frankosterfeld** [comment]
I don't know, I never compiled for openwrt. I assume it works like any other CMake-based project. Are you cross-compiling or building natively?

**Comment by linamu** [comment]
i'm cross-compiling, i think i should create a qtkeychain package for openwrt with a makefile and compile it 
thank you for answering me :)

**Comment by linamu** [comment]
sorry for bothering you @frankosterfeld 

can you help me with this ? 
/lib/i386-linux-gnu/libQt5DBus.so.5.4.2: could not read symbols: File in wrong format
collect2: ld returned 1 exit status

**Comment by frankosterfeld** [comment]
What's the context? What are you building? Is this actually the right lib (looks like a system path, not a location for cross-compiled code). Did you build Qt for openwrt with dbus support? I can't help you debugging generic cross-compilation issues with openwrt, for that it would probably be better to check for OpenWRT mailing lists or IRC channels.

**Comment by frankosterfeld** [comment]
Closing, please reopen if there's an issue remaining with current qtkeychain
