### ISSUE TITLE
error while installing qtkeychain with brew on OSX

### ISSUE THREAD

**Issue by kramer65** [frankosterfeld/qtkeychain#72]
For compiling some software I need `qtkeychain` to be installed with brew, so I ran

    brew install qtkeychain

which results in the following:

    $ brew install qtkeychain
    ==> Installing qtkeychain from owncloud/owncloud
    ==> Downloading https://github.com/frankosterfeld/qtkeychain/archive/0.3.tar.gz
    Already downloaded: /Library/Caches/Homebrew/qtkeychain-0.3.tar.gz
    Warning: SHA1 support is deprecated and will be removed in a future version.
    Please switch this formula to SHA256.
    ==> cmake . -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qtkeychain/0.3 -DCMAKE_BUILD_TYPE=Release -
    ==> make install
    Last 15 lines from /Users/kramer65/Library/Logs/Homebrew/qtkeychain/02.make:
    /usr/local/opt/qt5/lib/QtCore.framework/Headers/qtypetraits.h:492:1: error: C++ requires a type specifier for all declarations
    Q_STATIC_ASSERT((!is_unsigned<qint16>::value));
    ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make[2]: *** [CMakeFiles/qt5keychain.dir/moc_keychain.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    20 errors generated.
    make[2]: *** [CMakeFiles/qt5keychain.dir/moc_keychain_p.cpp.o] Error 1
    20 errors generated.
    make[2]: *** [CMakeFiles/qt5keychain.dir/keychain.cpp.o] Error 1
    20 errors generated.
    make[2]: *** [CMakeFiles/qt5keychain.dir/keychain_mac.cpp.o] Error 1
    make[1]: *** [CMakeFiles/qt5keychain.dir/all] Error 2
    make: *** [all] Error 2

I made sure that brew was up to date (`brew update`) and fixed as many issues reported by `brew doctor` with only [these two][1] remaining. I'm not sure if they matter for the issue I'm having.

I'm unsure of what I can do to fix this. So I already reported it [on stackexchange here](http://apple.stackexchange.com/questions/235693/brew-install-qtkeychain-fails-with-some-weird-error?noredirect=1#comment288897_235693), on the githubpage of [homebrew core here](https://github.com/Homebrew/homebrew-core/issues/513#event-636354404) and on the github page of the [brew owncloud formula here](https://github.com/owncloud/homebrew-owncloud/issues/5), but no one seems to know a way to fix this.

Do you guys know what I can do to solve this? I'm quite desperate, so any help would be really really appreciated.

  [1]: http://pastebin.com/mkz8qauL

**Comment by danimo** [comment]
Ok, finally got the chance to work on this on a real mac. The fomula now builds for me without warnings.

**Comment by danimo** [comment]
Lets track this over in https://github.com/owncloud/homebrew-owncloud/issues/5. @frankosterfeld you can close this one.

**Comment by frankosterfeld** [comment]
Thanks

**Comment by iVanilla** [comment]
The qtkeychain is not found.
`brew install qtkeychain`

```
Error: No available formula with the name "qtkeychain" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```
