### ISSUE TITLE
Building with qmake?

### ISSUE THREAD

**Issue by pbek** [frankosterfeld/qtkeychain#91]
Thank you for this great library!
Is there any chance to make it build with a qmake based project like https://github.com/pbek/QOwnNotes? I see that you are generating a `qkeychain_export.h` with cmake.

**Comment by iamsergio** [comment]
qkeychain_export.h is an installed header which you can include

**Comment by pbek** [comment]
Thank you for your answer. But `qkeychain_export.h` will be generated by cmake on the system that builds the library (I guess dependent on the platform). Is there a way to create it with qmake?

**Comment by olear** [comment]
https://github.com/olear/qtkeychain/blob/master/qtkeychain.pro

Works for me. You can also just integrate the project into your existing Qt project very easily:
```pri
HEADERS += qtkeychain/keychain.h qtkeychain/keychain_p.h qtkeychain/qkeychain_export.h
SOURCES += qtkeychain/keychain.cpp

win32 {
    SOURCES += qtkeychain/keychain_win.cpp
    LIBS += -lCrypt32
}

mac {
    SOURCES += qtkeychain/keychain_mac.cpp
    LIBS += -framework CoreFoundation
    LIBS += -framework Security
}

unix:!mac {
    QT += dbus xml
    HEADERS += qtkeychain/gnomekeyring_p.h qtkeychain/kwallet_interface.h
    SOURCES += qtkeychain/gnomekeyring.cpp qtkeychain/keychain_unix.cpp qtkeychain/kwallet_interface.cpp
    OTHER_FILES += qtkeychain/org.kde.KWallet.xml
}
```

**Comment by pbek** [comment]
Thanks a lot @olear! I will try that!

**Comment by frankosterfeld** [comment]
There's also a qtkeychain.pri now that you can include in your project

**Comment by pbek** [comment]
awesome, thank you very much!
