### ISSUE TITLE
Cannot compile on macOS Sierra Qt 5.7

### ISSUE THREAD

**Issue by kildevaeld** [frankosterfeld/qtkeychain#92]
The moc compiler fails, because of a forward declaration to `QDBusPendingCallWatcher` in `keychain_p.h`.

**Comment by frankosterfeld** [comment]
Cannot reproduce (macos 10.12.4, XCode 8.3.2, Qt 5.7.1) , the types are declared but never used, so it shouldn't be a problem?

**Comment by frankosterfeld** [comment]
Closing, please reopen if you still see this with latest master or 0.8 branches.
