### ISSUE TITLE
kwalletWalletFound slot

### ISSUE THREAD

**Issue by art926** [frankosterfeld/qtkeychain#96]
When moc process keychain_p.h it doesn't know constants like Q_OS_UNIX, Q_OS_DARWIN, etc. That's why in class ReadPasswordJobPrivate  we can see two sets of kwalletOpenFinished, kwalletEntryTypeFinished and kwalletFinished starting with  'private Q_SLOTS'.  However, in  class JobPrivate  else section doesn't start with 'protected Q_SLOTS', which leads moc to think that it's a regular function, not a slot. So, it's impossible to connect to kwalletOpenFinished slot later.

**Comment by frankosterfeld** [comment]
This was fixed meanwhile I believe, by adding stubs for kwalletOpenFinished etc. on all platforms
