### ISSUE TITLE
Request for new tagged release

### ISSUE THREAD

**Issue by dakcarto** [frankosterfeld/qtkeychain#98]
Hi. Thanks for you work on QtKeychain. 

I'd like to request an incremental tagged release, e.g. 0.8.0, to aid in submitting a new `qtkeychain` [Homebrew formula](https://github.com/dakcarto/homebrew-core/commit/2e06aea) for macOS.

**Comment by frankosterfeld** [comment]
0.8.0 released

**Comment by dakcarto** [comment]
Thanks!
